Repository haru/redmine_ai_helper, pull requests merged in 2025-06, with the labels that each got.

#37 Create fa.yml
  config/locales/fa.yml
Labels: enhancement

#38 implementing sub issues generator(#24)
  app/controllers/ai_helper_controller.rb
  app/views/ai_helper/subissue_gen/_index.html.erb
  app/views/ai_helper/subissue_gen/_issue_description_bottom.html.erb
  app/views/ai_helper/subissue_gen/_issues.html.erb
  assets/javascripts/ai_helper.js
  assets/prompt_templates/issue_agent/sub_issues_draft.yml
  assets/prompt_templates/issue_agent/sub_issues_draft_ja.yml
  assets/stylesheets/ai_helper.css
  config/locales/en.yml
  config/locales/ja.yml
  config/routes.rb
  init.rb
  lib/redmine_ai_helper/agents/issue_agent.rb
  lib/redmine_ai_helper/llm.rb
  lib/redmine_ai_helper/tools/issue_update_tools.rb
  lib/redmine_ai_helper/view_hook.rb
  test/functional/ai_helper_controller_test.rb
  test/unit/agents/issue_agent_test.rb
  test/unit/langfuse_util/gemini_test.rb
  test/unit/llm_test.rb
  test/unit/tools/issue_tools_test.rb
  test/unit/tools/issue_update_tools_test.rb
Labels: enhancement

#41 new github action added.
  .github/workflows/delete_merged_branch.yml
Labels: ignore-for-release

#55 Unify loading messages to use animated dot loader
  app/views/ai_helper/_issue_bottom.html.erb
  app/views/ai_helper/_issue_form.html.erb
  app/views/ai_helper/_wiki_summary.html.erb
  assets/javascripts/ai_helper.js
  config/locales/en.yml
  config/locales/fa.yml
  config/locales/ja.yml
Labels: Refactoring

#61 Permisstion check for health report
  app/views/ai_helper/_project_health.html.erb
Labels: ignore-for-release

#63 Fix broken javascript
  assets/javascripts/ai_helper_project_health.js
  lib/redmine_ai_helper/tools/project_tools.rb
Labels: ignore-for-release

#70 Prevent McpAgent from being selected when no MCP servers(#69)
  lib/redmine_ai_helper/agents/mcp_agent.rb
  lib/redmine_ai_helper/base_agent.rb
  test/unit/agents/agents_test.rb
  test/unit/base_agent_test.rb
Labels: Refactoring

#77 Fix Project Health Report CSS to match Redmine standards(#76)
  app/views/ai_helper/_project_health.html.erb
  assets/stylesheets/ai_helper.css
Labels: Refactoring
